[toolchain]

[features]
seeds = false
skip-lint = false

[workspace]
resolver = "2"

[programs.devnet]
using_spl_simplified = "cWBawXsh3Xvo4LjrTSCGQPAskNeiNn1dNGq4T8ZNiq6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/empiric-u3/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
